version: '3'
services: 

  cayamariadb:
    container_name: cayamariadb
    build: ./mariadb-alpine
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=cayaradsql
      - MYSQL_USER=ucaya
      - MYSQL_PASSWORD=passcaya-2019
      - MYSQL_ROOT_PASSWORD=cayapsql-19
    volumes:
      - ../docker-data/cayamariadb/storage:/var/lib/mysql
      - ../docker-data/cayamariadb/share:/share
      - ../docker-config/cayamariadb/my.cnf.d:/etc/my.cnf.d
    healthcheck:
      test: "nc -z localhost 3306"
      interval: 1s
      retries: 120
  
  cayarad:
    restart: on-failure
    container_name: cayarad
    build: freerad-alpine/.
    environment:
      - radiusdbserver=cayamariadb
      - radiusdbusername=ucaya
      - radiusdbpassword=passcaya-2019
      - radiusdbport=3306
      - radiusdbname=cayaradsql
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
      - 1814:1814/udp
    depends_on:
      - cayamariadb
    links:
      - cayamariadb

  cayadalo:
    restart: on-failure
    container_name: cayadalo
    build: ./dalo-alpine
    environment:
      - MYSQL_HOST=cayamariadb
      - APACHE_SERVER_NAME=cayadalo.docker.localhost
      - PHP_SHORT_OPEN_TAG=On
      - PHP_ERROR_REPORTING="E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED"
      - PHP_DISPLAY_ERRORS=Off
      - PHP_HTML_ERRORS=Off
      - PHP_XDEBUG_ENABLED=true
    ports:
      - 8000:80/tcp
    depends_on:
      - cayamariadb
    links:
      - cayamariadb